export enum AdminOptionEnums {
  CLASSES = "CLASSES",
  ACCOUNT = "ACCOUNT",
  COACHES = "COACHES",
  NEWS = "NEWS",
  NOTIFICATION = "NOTIFICATION",
  CLASS_LEVEL_RECORD = "CLASS_LEVEL_RECORD",
}

export enum AdminClassesOptionEnums {
  REGULAR_CLASSES = "REGULAR_CLASSES",
  COMING_CLASSES = "COMING_CLASSES",
  CLASSES_IN_PAST = "CLASSES_IN_PAST",
  SET_DAY_OFF = "SET_DAY_OFF",
  CONFIRMED_CLASSES = "CONFIRMED_CLASSES",
}
export enum AdminAccountFilterOptionEnums {
  ALL = "All",
  HAS_CLASSES = "HAS_CLASSES",
  NO_CLASSES = "NO_CLASSES",
}

export enum AdminPeriodOptionsEnum {
  ONE_DAY = "ONE_DAY",
  ONE_WEEK = "ONE_WEEK",
  ONE_MONTH = "ONE_MONTH",
  ONE_YEAR = "ONE_YEAR",
  ALL = "ALL",
}

export enum AdminViewAccountOptionEnums {
  VIEW_ACCOUNT = "VIEW_ACCOUNT",
  VIEW_UNUSED_CLASS = "VIEW_UNUSED_CLASS",
  VIEW_USED_CLASS = "VIEW_USED_CLASS",
  VIEW_CONFIRM_GRANT_AUTH = "VIEW_CONFIRM_GRANT_AUTH",
}
export enum AdminViewCoachOptionEnums {
  VIEW_ACCOUNT = "VIEW_ACCOUNT",
  REMOVE_COACH_CONFIRM = "REMOVE_COACH_CONFIRM",
  VIEW_COACH_INFO = "VIEW_COACH_INFO",
}

export enum AdminJoinLevelEnums {
  ALL = "All",
  JOIN_LOWER_LEVEL = "JOIN_LOWER_LEVEL",
  JOIN_HIGHER_LEVEL = "JOIN_HIGHER_LEVEL",
}
