export enum NotificationEnums {
  JOIN_CLASS = "JOIN_CLASS",
  JOIN_DIFFERENT_CLASS = "JOIN_DIFFERENT_CLASS",
  CLASS_CANCELLED = "CLASS_CANCELLED",
  CLASS_CONFIRMED = "CLASS_CONFIRMED",
  CLASS_PENDING = "CLASS_PENDING",
  CLASS_UPDATED = "CLASS_UPDATED",
  CLASS_CREATED = "CLASS_CREATED",
  LEAVE_CLASS = "LEAVE_CLASS",
}
